/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AziendaUpdateDTO { 
    id?: string;
    nomeProduttore: string;
    cognomeProduttore: string;
    partitaIva: string;
    numeroPrivato: string;
    emailPrivata: string;
    codiceFiscale: string;
    tesseramentoAttivo?: boolean;
    nomeAzienda: string;
    ragioneSociale: string;
    numeroAzienda: string;
    emailAzienda: string;
    comune: string;
    provincia: string;
    indirizzo: string;
    cap: string;
    descrizioneBreve?: string;
    descrizioneLunga?: string;
    linkFacebook?: string;
    linkYoutube?: string;
    linkInstagram?: string;
    linkWebsite?: string;
    linkTicToc?: string;
    tipoProdotto?: string;
    password: string;
    image1?: string;
    image2?: string;
    image3?: string;
    image4?: string;
    image5?: string;
}

