/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AziendaCreateDTO { 
    nomeProduttore: string;
    cognomeProduttore: string;
    partitaIva: string;
    numeroPrivato: string;
    emailPrivata: string;
    codiceFiscale: string;
    nomeAzienda: string;
    ragioneSociale: string;
    numeroAzienda: string;
    emailAzienda: string;
    comune: string;
    provincia: string;
    indirizzo: string;
    cap: string;
    password: string;
}

