/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComuneDTO } from './comune-dto';
import { ProduttoreDTO } from './produttore-dto';
import { ProvinciaDTO } from './provincia-dto';


export interface AziendaDTO { 
    id?: string;
    nome?: string;
    numeroPubblico?: string;
    email?: string;
    produttore?: ProduttoreDTO;
    comune?: ComuneDTO;
    provincia?: ProvinciaDTO;
}

